//! Behavior oracle for the storage transition paths: every sanitized adapter
//! fixture snapshot is replayed through a file-backed `Storage` together with
//! registration, binding, exit, stale-working expiry, and reconciliation, and
//! the resulting rows are compared with a committed snapshot. Set
//! `UPDATE_SNAPSHOTS=1` to rewrite the snapshot after an intentional change.

use super::*;
use chrono::{DateTime, TimeZone};
use serde_json::{Value, json};
use sessiontap_core::domain::{
    Capabilities, EventEvidence, EventKind, ProcessMetadata, PublicStatus, ToolActivityPhase,
};
use std::{fs, path::PathBuf};

fn base() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2000, 1, 1, 0, 0, 0).unwrap()
}

fn invocation_id(index: usize) -> InvocationId {
    InvocationId(uuid::Uuid::from_u128(
        0x0000_0000_0000_4000_8000_0000_0000_0000 + index as u128 + 1,
    ))
}

fn registered(index: usize, provider: &str) -> InvocationSnapshot {
    let now = base();
    InvocationSnapshot {
        schema_version: sessiontap_core::SCHEMA_VERSION,
        revision: 0,
        invocation_id: invocation_id(index),
        provider: provider.into(),
        executable: provider.into(),
        args: vec![],
        cwd: "/work/project".into(),
        process: ProcessMetadata {
            wrapper_pid: 10,
            ..Default::default()
        },
        created_at: now,
        updated_at: now,
        lifecycle: Lifecycle::Starting,
        activity: Activity::Unknown,
        state_started_at: now,
        last_state_asserted_at: None,
        activity_confirmation: ActivityConfirmation::Live,
        last_evidence: None,
        source_ordering: vec![],
        current_tool_activity: None,
        status: PublicStatus::Idle,
        provider_session: None,
        provider_metadata: None,
        usage: None,
        repository: None,
        multiplexer: None,
        capabilities: Capabilities::default(),
        turn_generation: 0,
        completed_generation: None,
        children: Vec::new(),
    }
}

fn fixture_snapshots() -> Vec<(String, Vec<Value>)> {
    let root =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../sessiontap-adapters/tests/snapshots");
    let mut paths = fs::read_dir(&root)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect::<Vec<_>>();
    paths.sort();
    paths
        .into_iter()
        .map(|path| {
            let name = path.file_stem().unwrap().to_string_lossy().into_owned();
            let cases: Vec<Value> =
                serde_json::from_str(&fs::read_to_string(&path).unwrap()).unwrap();
            (name, cases)
        })
        .collect()
}

/// Turns one masked adapter snapshot case into a concrete event with a
/// deterministic identity and timestamp.
fn concrete_event(
    case: &Value,
    id: &InvocationId,
    event_id: String,
    at: DateTime<Utc>,
) -> Option<(NormalizedEvent, Option<StatusReasonContext>)> {
    if case["outcome"] != "event" {
        return None;
    }
    let mut event = case["event"].clone();
    let object = event.as_object_mut().unwrap();
    object.insert("event_id".into(), json!(event_id));
    object.insert("invocation_id".into(), json!(id.to_string()));
    object.insert("received_at".into(), json!(at));
    if object["observed_at"] == "<received_at>" {
        object.insert("observed_at".into(), json!(at));
    }
    let event = serde_json::from_value(event).unwrap();
    let reason = serde_json::from_value(case["status_reason"].clone()).unwrap();
    Some((event, reason))
}

fn applied(update: Option<&AppliedUpdate>) -> Value {
    update.map_or(Value::Null, |update| {
        json!({
            "revision": update.revision,
            "delivery_id": update.delivery_id,
            "changed": update.changed,
            "view": update.view,
        })
    })
}

/// Replaces wall-clock timestamps with a stable marker. Every fixed test time
/// lies in the year 2000, so anything else was generated by `Utc::now()`.
fn mask(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for (key, value) in map.iter_mut() {
                if matches!(
                    key.as_str(),
                    "updated_at" | "stopped_at" | "committed_at" | "next_attempt_at"
                ) && value.as_str().is_some_and(|raw| !raw.starts_with("2000-"))
                {
                    *value = json!("<wall-clock>");
                } else {
                    mask(value);
                }
            }
        }
        Value::Array(values) => values.iter_mut().for_each(mask),
        _ => {}
    }
}

fn dump(db: &Storage) -> Value {
    let conn = db.conn.lock().unwrap();
    let revision: u64 = conn
        .query_row(
            "SELECT value FROM broker_meta WHERE key='revision'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    let rows = |sql: &str, f: &dyn Fn(&rusqlite::Row<'_>) -> rusqlite::Result<Value>| {
        let mut stmt = conn.prepare(sql).unwrap();
        stmt.query_map([], |row| f(row))
            .unwrap()
            .collect::<rusqlite::Result<Vec<_>>>()
            .unwrap()
    };
    let parse = |raw: String| serde_json::from_str::<Value>(&raw).unwrap();
    let invocations = rows(
        "SELECT invocation_id,provider,snapshot_json,stopped_at,turn_generation,completed_generation FROM invocations ORDER BY rowid",
        &|r| {
            Ok(json!({
                "invocation_id": r.get::<_, String>(0)?,
                "provider": r.get::<_, String>(1)?,
                "snapshot": parse(r.get(2)?),
                "stopped_at": r.get::<_, Option<String>>(3)?,
                "turn_generation": r.get::<_, u64>(4)?,
                "completed_generation": r.get::<_, Option<u64>>(5)?,
            }))
        },
    );
    let events = rows(
        "SELECT event_id,invocation_id,revision,received_at,event_json FROM normalized_events ORDER BY revision",
        &|r| {
            Ok(json!({
                "event_id": r.get::<_, String>(0)?,
                "invocation_id": r.get::<_, String>(1)?,
                "revision": r.get::<_, u64>(2)?,
                "received_at": r.get::<_, String>(3)?,
                "event": parse(r.get(4)?),
            }))
        },
    );
    let reasons = rows(
        "SELECT invocation_id,kind,reason_json FROM local_status_reasons ORDER BY invocation_id",
        &|r| {
            Ok(json!({
                "invocation_id": r.get::<_, String>(0)?,
                "kind": parse(r.get(1)?),
                "reason": parse(r.get(2)?),
            }))
        },
    );
    let outbox = rows(
        "SELECT sink_name,event_id,revision,payload,attempts FROM sink_outbox ORDER BY revision,sink_name",
        &|r| {
            Ok(json!({
                "sink_name": r.get::<_, String>(0)?,
                "event_id": r.get::<_, String>(1)?,
                "revision": r.get::<_, u64>(2)?,
                "payload": serde_json::from_slice::<Value>(&r.get::<_, Vec<u8>>(3)?).unwrap(),
                "attempts": r.get::<_, u32>(4)?,
            }))
        },
    );
    json!({
        "revision": revision,
        "invocations": invocations,
        "normalized_events": events,
        "local_status_reasons": reasons,
        "sink_outbox": outbox,
    })
}

#[test]
fn fixture_replay_matches_snapshot() {
    let temp = tempfile::tempdir().unwrap();
    let db = Storage::open(&temp.path().join("replay.sqlite3")).unwrap();
    let sinks = BTreeMap::from([
        (
            "hub".to_owned(),
            SinkConfig::Hub {
                enabled: true,
                url: "http://127.0.0.1:8931/ingest".into(),
                token_env: None,
                token_file: None,
                timeout_ms: 100,
                max_payload_bytes: 64 * 1024,
                trusted_addresses: vec![],
                fields: vec![],
            },
        ),
        (
            "observer".to_owned(),
            SinkConfig::Stdout {
                enabled: true,
                fields: vec![],
            },
        ),
    ]);
    let publish = Publish {
        sinks: &sinks,
        source_id: "replay",
        source_name: Some("Replay"),
    };
    let mut calls = Vec::new();
    let fixtures = fixture_snapshots();
    for (index, (name, cases)) in fixtures.iter().enumerate() {
        let provider = name.split('-').next().unwrap();
        let snapshot = registered(index, provider);
        let id = snapshot.invocation_id.clone();
        let credential = format!("credential-{index}");
        let revision = db.register(&snapshot, &credential, Some(&publish)).unwrap();
        calls.push(json!({"call": "register", "fixture": name, "revision": revision}));
        let pid = 1000 + u32::try_from(index).unwrap();
        let update = db
            .bind_child(
                &id,
                &credential,
                pid,
                Some(format!("start-{pid}")),
                Some(&publish),
            )
            .unwrap();
        calls.push(
            json!({"call": "bind_child", "fixture": name, "update": applied(update.as_ref())}),
        );
        for (position, case) in cases.iter().enumerate() {
            let at = base() + Duration::seconds(i64::try_from(position).unwrap() + 1);
            let Some((event, reason)) = concrete_event(case, &id, format!("{name}-{position}"), at)
            else {
                continue;
            };
            let update = db
                .apply_event_with_context(&event, reason.as_ref(), Some(&publish))
                .unwrap();
            calls.push(json!({
                "call": "apply_event",
                "event_id": event.event_id,
                "update": applied(update.as_ref()),
            }));
        }
        // Replay a late duplicate to exercise dedup.
        if let Some((event, reason)) = cases.iter().enumerate().find_map(|(position, case)| {
            concrete_event(case, &id, format!("{name}-{position}"), base())
        }) {
            let update = db
                .apply_event_with_context(&event, reason.as_ref(), Some(&publish))
                .unwrap();
            calls.push(json!({"call": "duplicate", "event_id": event.event_id, "update": applied(update.as_ref())}));
        }
        if index % 3 == 0 {
            let update = db
                .mark_exit(&id, &credential, Some(0), None, Some(&publish))
                .unwrap();
            calls.push(
                json!({"call": "mark_exit", "fixture": name, "update": applied(update.as_ref())}),
            );
        }
    }

    // A dedicated long-running tool turn for explicit stale-working expiry.
    let stale_index = fixtures.len();
    let stale = registered(stale_index, "claude");
    db.register(&stale, "stale", Some(&publish)).unwrap();
    db.bind_child(&stale.invocation_id, "stale", 4242, None, Some(&publish))
        .unwrap();
    let mut working = NormalizedEvent {
        schema_version: 1,
        event_id: "stale-working".into(),
        invocation_id: stale.invocation_id.clone(),
        provider_event_id: None,
        provider: "claude".into(),
        observed_at: base(),
        received_at: base() + Duration::seconds(1),
        evidence: EventEvidence::managed_hook(1),
        kind: EventKind::Working,
        provider_session_id: Some("stale-session".into()),
        provider_session_name: None,
        provider_session_start_reason: None,
        provider_metadata: None,
        usage: None,
        turn_id: None,
        tool_activity: Some(sessiontap_core::domain::ToolActivityUpdate {
            phase: ToolActivityPhase::Start,
            label: "shell".into(),
            correlation_id: Some("long".into()),
            detail: None,
        }),
        child_agent: None,
    };
    db.apply_event_with_context(&working, None, Some(&publish))
        .unwrap();
    working.event_id = "stale-working-refresh".into();
    working.received_at = base() + Duration::minutes(10);
    db.apply_event_with_context(&working, None, Some(&publish))
        .unwrap();
    for minutes in [30, 40, 41] {
        let updates = db
            .expire_stale_working_at(base() + Duration::minutes(minutes), Some(&publish))
            .unwrap();
        calls.push(json!({
            "call": "expire_stale_working_at",
            "minutes": minutes,
            "updates": updates.iter().map(|u| applied(Some(u))).collect::<Vec<_>>(),
        }));
    }

    // Fixtures with index % 3 == 1 have a dead process; % 3 == 2 are alive.
    let changed = db
        .reconcile(
            |pid, _| pid >= 1000 && (pid - 1000) % 3 == 2,
            7,
            Some(&publish),
        )
        .unwrap();
    calls.push(json!({"call": "reconcile", "changed": changed}));
    let changed = db.reconcile(|_, _| false, 7, Some(&publish)).unwrap();
    calls.push(json!({"call": "reconcile_all_dead", "changed": changed}));

    let mut actual = json!({"calls": calls, "state": dump(&db)});
    mask(&mut actual);
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/replay/storage-replay.json");
    let rendered = serde_json::to_string_pretty(&actual).unwrap() + "\n";
    if std::env::var_os("UPDATE_SNAPSHOTS").is_some() {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, rendered).unwrap();
        return;
    }
    let expected = fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing {}; run with UPDATE_SNAPSHOTS=1", path.display()));
    assert!(
        expected == rendered,
        "storage replay diverged from {}; rerun with UPDATE_SNAPSHOTS=1 only for an intentional change",
        path.display()
    );
}
